# ~/.config/starship.tom

format = """
[](fg:#3c3836)\
$os\
$username\
[](bg:#504945 fg:#3c3836)\
$directory\
[](fg:#504945 bg:#665c54)\
$git_branch\
$git_status\
[](fg:#665c54 bg:#d79921)\
$kubernetes\
[](fg:#d79921 bg:#928374)\
$docker_context\
[](fg:#928374 bg:#b8bb26)\
$golang\
[](fg:#b8bb26 bg:#83a598)\
$dotnet\
[](fg:#83a598)\
$line_break\
$character"""

[os]
disabled = false
style = "bg:#3c3836 fg:#ebdbb2"
format = "[ $symbol ]($style)"

[os.symbols]
Arch = "󰣇"

[username]
show_always = false
style_user = "bg:#3c3836 fg:#ebdbb2"
format = '[ $user ]($style)'

[directory]
style = "fg:#ebdbb2 bg:#504945"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Developer" = "󰲋 "
"Projects" = "󰲋 "

[git_branch]
symbol = ""
style = "bg:#665c54"
format = '[[ $symbol $branch ](fg:#ebdbb2 bg:#665c54)]($style)'

[git_status]
style = "bg:#665c54"
format = '[[($all_status$ahead_behind )](fg:#ebdbb2 bg:#665c54)]($style)'
ahead = '⇡${count}'
behind = '⇣${count}'
diverged = '⇕${ahead_count}⇣${behind_count}'
untracked = '?${count}'
modified = '!${count}'
staged = '+${count}'
deleted = '✘${count}'

[kubernetes]
disabled = false
symbol = "☸ "
format = '[[ $symbol$context( \($namespace\)) ](fg:#282828 bg:#d79921 bold)]($style)'
style = "bg:#d79921"
detect_files = []
detect_folders = []
detect_extensions = []

[kubernetes.context_aliases]
"aks-prod-we-vks" = "prod"
"aks-qa-we-vks" = "qa"
"aks-dev-we-vks" = "dev"
"docker-desktop" = "local"

[[kubernetes.contexts]]
context_pattern = ".*prod.*"
style = "bg:#fb4934 fg:#282828 bold"
symbol = "☸ PROD "

[[kubernetes.contexts]]
context_pattern = ".*dev.*"
style = "bg:#b8bb26 fg:#282828 bold"
symbol = "☸ DEV "

[[kubernetes.contexts]]
context_pattern = ".*staging.*|.*stage.*"
style = "bg:#fabd2f fg:#282828 bold"
symbol = "☸ STAGE "

[docker_context]
symbol = ""
style = "bg:#928374"
format = '[[ $symbol $context ](fg:#3c3836 bg:#928374)]($style)'
detect_files = ['docker-compose.yml', 'Dockerfile']

[golang]
symbol = ""
style = "bg:#b8bb26 fg:#3c3836"
format = '[[ $symbol ($version) ](fg:#3c3836 bg:#b8bb26 bold)]($style)'
detect_extensions = ['go']
detect_files = ['go.mod', 'go.sum']

[dotnet]
symbol = "󰪮"
style = "bg:#83a598 fg:#3c3836"
format = '[[ $symbol ($version) ](fg:#3c3836 bg:#83a598 bold)]($style)'
detect_extensions = ['csproj', 'fsproj', 'xproj', 'sln']
detect_files = ['global.json', 'project.json', 'Directory.Build.props']

[character]
success_symbol = '[](bold fg:#b8bb26)'
error_symbol = '[](bold fg:#fb4934)'
vimcmd_symbol = '[](bold fg:#b8bb26)'

[line_break]
disabled = false

[cmd_duration]
min_time = 500
format = '[ took $duration ]($style)'
style = "fg:#928374"
